#  <font color='303B65'>**Alivio Capital.** </font> <font color='1C84E6'>**Análisis de Solicitudes.** </font> 

![Análisis estádistico ](https://www.ceupe.com/images/easyblog_articles/1305/planificacion-financiera.jpg)

## **Índice**   
1. [Introducción](#id1) <br>
<space><space><space><space> 1.1. [Conceptos Básicos](#id1.1)<br>
<space><space><space><space> 1.2. [Misión y visión](#id1.2)<br>
<space><space><space><space> 1.3. [Objetivos](#id1.3)<br>

## 1. Introducción <a name="id1"></a>

<font color='0A9299'>**Alivio Capital** </font> es una financiera encargada de financiar/prestar casos médicos asi como productos y sus derivados.
De igual manera representa prestamos con diferente productos en el cual estos son productos como:
* <font color='B60B35'>**Médico:** </font> Prestamos médicos (producto principal)
* <font color='B60B35'>**MSI:** </font> Meses sin intereres
* <font color='B60B35'>**KIVA:** </font> Prestamos de caridad

Para poder analizar los perfiles de las solicitudes, tenemos que aterrizar los conceptos que tenemos acerca de estas y ver cuales son las <font color='C94844'>**solicitudes que mayormente son aceptadas** </font> , puesto que como tenemos conocimiento se tiene que escoger meticulosamente a que persona se le prestara para que nuestra cartera de clientes no caiga en mora/default

De igual manera, en el proceso de investigación encontraremos cual es mi <font color='C94844'>**mercado de clientes** </font> (que personas son las que mayormente me solicitan)

### 1.1. Conceptos Básicos <a name="id1.1"></a>

En esta parte de la investigación del mercado de clientes mediante la plataforma "Arból" donde se encuentra en reposicion la mayoria de las solicitudes que se han cargado al sistema, siendo esta compuesta por las solicitudes desde el año 2019.
En el cual existen tres tipos de solicitudes que los segmentaremos a lo largo del procesos de limpieza de datos:
1. <font color='B60B35'>**Imagen Dental:** </font> Solicitudes de clinicas de imagen dental asi como su personal
2. <font color='B60B35'>**Asistidas:** </font> Solicitudes cargadas por el personal de la financiera de Alivio Capital
3. <font color='B60B35'>**Autoservicio:** </font> Solicitudes que son cargadas por mediante la pagina web

### 1.2. Misión y visión <a name="id1.2"></a>

Con este estudio de mercado se piensa obtener información que ayude a la dirección en la toma de decisiones para poder incrementar las solicitudes de autoservicio y asisitidas para incrementar las ventas
De igual manera con estos metodos estadisticos se busca el perfil con mayor probabilidad de aceptar las solicitud

Nuestra misión con este estudio sera: <font color='0A9299'>**"Aplicar métodos estadisticos sostifiscados para poder realizar analisis produndos"** </font>

y nuestra visión con esta investigación: <font color='0A9299'>**"Encontrar puntos en donde encontremos fallos y oportunidades para poder aprovechar dicho mercado""** </font>

### 1.3. Objetivos <a name="id1.3"></a>

#### 1.3.1. Objetivos Principales <a name="id1.3.1"></a>

1. Comprender el comportamiento de las solicitudes
2. Encontrar los mejores perfiles de clientes para mi cartera de clientes
3. Predecir futuros comportamientos

#### 1.3.2. Objetivos Secundarios <a name="id1.3.2"></a>

1. Visualizar mis variables
2. Concluir acerca de mi estadisticas
3. Inferir casos estadisticos
4. Realizar modelos de IA para conseguir clientes objetivos 
5. Visualizar mis modelos IA

## 2. Carga y lectura de datos <a name="id2"></a>

In [4]:
# Importamos librerias necesarias para poder leer y trabajar los datos
import pandas as pd 
import os
import numpy as np
import matplotlib.pyplot as plt

In [24]:
# Leemos nuestra base de datos
ruta = "C:/Users/Alivio/Documents/ALIVIO CAPITAL/BUSINESS INTELLIGENCE/BASES DE DATOS/"
df = pd.read_csv(ruta + "SOCIOS COMERCIALES.csv")

In [25]:
# Visualizamos las primeras filas de nuestro datasets
df.head()

,Categoria Contable,Producto,Contrato,Cliente,Fecha Inicial,Fecha Compra,No. Pagos,Total Pagos,Precio,Enganche,...,Distribuidor,Ejecutivo,Zona,Promotora,Embajadora,Distribuidor Homologado,Column1,Sucursal,Hospital / Clinica / Medico,Especialidad
0,CONSUMO,CREDITO KIVA MEDICO,088147-2360093-01,YAMILETH NOEMI VALENCIA CARDENAS,02/01/2020,02/01/2020,12,"$9,567.36","$8,192.00",$0.00,...,CLINICA DENTAL,CYNTHIA MORALES,CDMX,PAOLA AROZENA,S/E,"LA CLINICA DENTAL, S.A. DE C.V.",OTRO,NaN,CLINICA,ODONTOLOGIA
1,CONSUMO,CREDITO NOMIFACIL,071048-2350093-01,FIDENCIO GPE GUERRERO RODEA,02/01/2020,02/01/2020,12,"$17,782.32","$12,000.00",$0.00,...,DOCTORS HOSPITAL,YENILY BALLESTERO,MTY,SUSANA ROJAS,S/E,"DOCTORS HOSPITAL, S.A. DE C.V.",OTRO,NaN,HOSPITAL,CIRUGIA GENERAL
2,CONSUMO,CREDITO NOMIFACIL,076377-2350113-01,ROMEO ALEJANDRO GARZA NAVARRO,02/01/2020,02/01/2020,24,"$41,164.80","$20,000.00",$0.00,...,PERSONAL,ELVIRA PEREZ,DIGITAL,NaN,S/E,PERSONAL,OTRO,NaN,NaN,NaN
3,CONSUMO,CREDITO NOMIFACIL,082417-2350103-01,ROCIO ADRIANA CRUZ LUNA,02/01/2020,02/01/2020,18,"$21,402.90","$12,000.00",$0.00,...,PERSONAL,XOCHITL VALDES,MTY,LIZETH SALAS,S/E,PERSONAL,OTRO,NaN,NaN,NaN
4,CONSUMO,CRED MEDICO ACUERDO COMERCIAL,088094-3110093-01,MARLENE DEL ROCIO TOVAR SOLANO,02/01/2020,02/01/2020,12,"$9,588.00","$7,253.00",$0.00,...,SONRIA ARAGON,SONRIA,CDMX,ANA KARIN CRUZ RODRIGUEZ,S/E,"SONRIA, S.A. DE C.V.",OTRO,(ARAGON),CLINICA,ODONTOLOGIA

In [27]:
# Mostramos los titulos de nuestras columnas
df.columns.values

array(['Categoria Contable', 'Producto', 'Contrato', 'Cliente',
       'Fecha Inicial', 'Fecha Compra', 'No. Pagos', 'Total Pagos',
       'Precio', 'Enganche', 'Monto A Financiar', 'Valor Residual',
       'Opcion Compra', 'Rentas En Deposito', 'Tasa', 'Total Interes',
       'Total Iva', 'Moneda', 'Gerente', 'Distribuidor', 'Ejecutivo',
       'Zona', 'Promotora', 'Embajadora', 'Distribuidor Homologado',
       'Column1', 'Sucursal', 'Hospital / Clinica / Medico',
       'Especialidad'], dtype=object)

In [28]:
df.tail(8) #observamos las ultimas 8 filas

,Categoria Contable,Producto,Contrato,Cliente,Fecha Inicial,Fecha Compra,No. Pagos,Total Pagos,Precio,Enganche,...,Distribuidor,Ejecutivo,Zona,Promotora,Embajadora,Distribuidor Homologado,Column1,Sucursal,Hospital / Clinica / Medico,Especialidad
6597,CONSUMO,CREDITO NOMIFACIL,098218-2350083-01,BLANCA ESTHELA LUNA MENDOZA,31/05/2022,31/05/2022,$6.00,"$5,100.12","$4,000.00",$0.00,...,PERSONAL,BALTAZAR SILVA,FORANEO,LOURDES FLANDES,S/E,NaN,0,NaN,NaN,NaN
6598,CONSUMO,CREDITO KIVA MEDICO,095441-2410093-01,LEONEL HERNANDEZ RAMIREZ,31/05/2022,31/05/2022,$12.00,"$20,165.40","$15,000.00",$0.00,...,"VE MAS CALIDAD A LA VISTA, S. DE R.L. DE C.V.",VE MAS,MTY,CONY MONTALVO,S/E,NaN,0,NaN,NaN,NaN
6599,CONSUMO,CREDITO MEDICO ALIVIO,098215-2310093-01,JOSE MANUEL RUIZ ORTIZ,31/05/2022,31/05/2022,$12.00,"$103,913.52","$70,000.00",$0.00,...,DR. JESUS ANTONIO GIL GAMEZ,BALTAZAR SILVA,FORANEO,LOURDES FLANDES,LUIS MANUEL VAZQUEZ PÉREZ,NaN,0,NaN,NaN,NaN
6600,CONSUMO,CREDITO MEDICO ALIVIO,098013-2310083-01,DAFNE PAOLA DOMINGUEZ RODRIGUEZ,31/05/2022,31/05/2022,$6.00,"$38,318.82","$30,000.00",$0.00,...,DR. CARLOS ALBERTO ABUNDIS PALMA Y MEZA,LUZMARBI RAMIREZ,DIGITAL,LUZMARBI RAMIREZ,S/E,NaN,0,NaN,NaN,NaN
6601,CONSUMO,CREDITO KIVA MEDICO,098106-2410093-01,INES TREJO CASTILLO,31/05/2022,31/05/2022,$12.00,"$8,066.16","$6,000.00",$0.00,...,OIDOS PARA OIR,BALTAZAR SILVA,FORANEO,LOURDES FLANDES,ALVARO MANUEL HERNÁNDEZ ESPARZA,NaN,0,NaN,NaN,NaN
6602,CONSUMO,CREDITO KIVA MEDICO,098164-2410083-01,NIRIA YASMIN RAMIREZ HERNANDEZ,31/05/2022,31/05/2022,$6.00,"$12,015.78","$10,000.00",$0.00,...,"VE MAS CALIDAD A LA VISTA, S. DE R.L. DE C.V.",VE MAS,MTY,CONY MONTALVO,S/E,NaN,0,NaN,NaN,NaN
6603,CONSUMO,CREDITO MEDICO ALIVIO,098206-2310083-01,IRMA CORDOVA MENDEZ,31/05/2022,31/05/2022,$6.00,"$36,218.04","$30,000.00",$0.00,...,DR. MARCO TULIO MARROQUIN BATRES,BALTAZAR SILVA,FORANEO,LOURDES FLANDES,S/E,NaN,0,NaN,NaN,NaN
6604,CONSUMO,CREDITO MEDICO ALIVIO,098214-2310113-01,NORMA ALICIA GARZA TORRES,31/05/2022,31/05/2022,$24.00,"$82,489.44","$40,000.00",$0.00,...,MANUEL GARCIA GARZA,DANIEL CHÁVEZ,MTY,GUADALUPE SANDOVAL,ELENA ARENAS,MANUEL GARCIA GARZA,0,NaN,NaN,NaN

In [29]:
df.shape # (numero de filas,numero de columnas)

(6605, 29)

In [30]:
df.describe() #resumen de los estadísticos básicos de las variables numéricas.

,Valor Residual,Opcion Compra,Rentas En Deposito,Tasa,Total Interes,Total Iva
count,6605.0,6605.0,6605.0,6605.000000,6605.000000,6605.000000
mean,0.0,0.0,0.0,50.823936,16496.313864,2636.437694
std,0.0,0.0,0.0,17.320974,34317.401209,5490.875707
min,0.0,0.0,0.0,0.000000,0.000000,-0.080000
25%,0.0,0.0,0.0,46.500000,1973.820000,314.220000
50%,0.0,0.0,0.0,58.000000,5613.000000,898.090000
75%,0.0,0.0,0.0,64.000000,18227.370000,2910.140000
max,0.0,0.0,0.0,64.000000,553516.580000,88562.660000

In [31]:
df.dtypes #mostraremos en pantalla el tipo de datos de mis variables

Categoria Contable              object
Producto                        object
Contrato                        object
Cliente                         object
Fecha Inicial                   object
Fecha Compra                    object
No. Pagos                       object
Total Pagos                     object
Precio                          object
Enganche                        object
Monto A Financiar               object
Valor Residual                   int64
Opcion Compra                    int64
Rentas En Deposito               int64
Tasa                           float64
Total Interes                  float64
Total Iva                      float64
Moneda                          object
Gerente                         object
Distribuidor                    object
Ejecutivo                       object
Zona                            object
Promotora                       object
Embajadora                      object
Distribuidor Homologado         object
Column1                         object
Sucursal                        object
Hospital / Clinica / Medico     object
Especialidad                    object
dtype: object